### ISSUE TITLE
create node failed

### ISSUE THREAD

**Issue by xiaopengzhang** [f5devcentral/terraform-provider-bigip-old#111]
* bigip_ltm_node.node_0: Found unexpected json pair at configuration item /ltm/node/~Common~terraform_node1. The json pair is "fqdn":{}.

how to resolve?

**Comment by scshitole** [comment]
@xiaopengzhang  can you please send the whole config like
```
resource "bigip_ltm_node" "node" {
  name = "/Common/terraform_node1"
  address = "10.10.10.10"
}
```

**Comment by xiaopengzhang** [comment]
I use f5 version is to low

**Comment by adam-f5** [comment]
Repository Archived
