### ISSUE TITLE
Need a resource for TCP Profile

### ISSUE THREAD

**Issue by nmontel** [f5devcentral/terraform-provider-bigip-old#114]
My LTM build needed a TCP Protocol Profile but there was not an F5 Terraform Resource that existed so I am having to build it manually.

**Comment by dannyk81** [comment]
a TCP profile can be created using the `bigip_ltm_profile_tcp` resource.

Documentation: https://github.com/f5devcentral/terraform-provider-bigip/blob/master/website/docs/r/bigip_ltm_profile_tcp.html.markdown

**Comment by adam-f5** [comment]
Repository Archived
