### ISSUE TITLE
bigip_ltm_policy with additional option

### ISSUE THREAD

**Issue by onurbrc** [f5devcentral/terraform-provider-bigip-old#129]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME
- bigip_ltm_policy

##### TERRAFORM VERSION
```
Terraform v0.11.14
+ provider.bigip v0.12.2
```

##### BIGIP VERSION
```
Main Package
  Product     BIG-IP
  Version     12.1.3.7
```

##### SUMMARY
Hi ! 

It would be nice being able to add http requests redirection to https for virtual servers listening on 80 which traffic must be on https ports instead. The CLI example as follow :

##### TMSH EXAMPLE

```
create ltm policy http2https
  strategy all-match
  requires add { http }
  controls add { forwarding }
  rules add {
    <RuleName> {
      actions replace-all-with {
        0 {
          http-reply redirect
          location ""https://[getfield [HTTP::host] \"":\"" 1][HTTP::uri]""
        }
      }
    }
  }

```

##### EXPECTED RESULTS
```
ltm policy http2https {
    controls { forwarding }
    requires { http }
    rules {
        http2https {
            actions {
                0 {
                    http-reply
                    redirect
                    location "tcl:https://[getfield [HTTP::host] \":\" 1][HTTP::uri]"
                }
            }
        }
    }
    status published
    strategy all-match
}
```

##### QUESTIONS 
Considering that bigip_ltm_policy resource already exists, how can I assign a policy to a given 
 bigip_ltm_virtual_server resource ? 

Thank you in advance.

**Comment by adam-f5** [comment]
Repository Archived
