### ISSUE TITLE
resource bigip_ltm_node expects fqdn

### ISSUE THREAD

**Issue by tecromatica** [f5devcentral/terraform-provider-bigip-old#130]
If using the example from the Terraform site, the node doesn't get created. Only "name" and "address" are required. 

resource "bigip_ltm_node" "node" {
  name = "/Common/terraform_node1"
  address = "10.10.10.10"
  }

Defaults for FQDN seem to be incorrect, error states: "The json pair is "fqdn":{}. Despite the fact i'm not specifying this optional parameter. It must be coming from the code.

**Comment by adam-f5** [comment]
Repository Archived
