### ISSUE TITLE
add Data Sources to the module

### ISSUE THREAD

**Issue by st33v** [f5devcentral/terraform-provider-bigip-old#61]
hello, I'd like to be able to use [terraform data sources](https://www.terraform.io/docs/configuration/data-sources.html) with this provider so that I can more easily reference objects in BigIP that i may or may not have created using terraform. 

We have some cases where we do not have a 1-to-1 correlation between server pools and VIPs. a single VIP in our environment might serve content from several backend server pools. If we could query the f5 for these pools and use that reference in our VIP definition, we'd be able to accommodate this requirement using terraform to manage our f5 configs.

**Comment by adam-f5** [comment]
Repository Archived
