### ISSUE TITLE
State and recommended usage?

### ISSUE THREAD

**Issue by magnusheino** [f5devcentral/terraform-provider-bigip-old#80]
Hi.

Found this project through https://devcentral.f5.com/articles/big-ip-terraform-resources-28924

Is this an official recommended/supported module by F5? 

It is production ready?

I notice that there are a few prebuilt releases on the github page, should I use those or is it recommended to build latest from source?

Thanks.

**Comment by scshitole** [comment]
@magnusheino please build from the latest source, you can follow the steps to build
go version
go version go1.9.2 darwin/amd64

mkdir workspace
export GOPATH=$HOME/workspace
mkdir -p $GOPATH/src/github.com/f5devcentral
cd $GOPATH
go get github.com/f5devcentral/terraform-provider-bigip
cd src/github.com/f5devcentral/terraform-provider-bigip/
go build
create .tf
terraform init
Initializing provider plugins...

Terraform has been successfully initialized!

**Comment by magnusheino** [comment]
What is "create .tf"? I don't have a create binary/command. I do get a binary built with "go build".

But the state of the plugin is good? It is usable, and expected to work? I dont mind building, just want to know :)

**Comment by dannyk81** [comment]
I think "create .tf" was referred to the step where you create the relevant terraform (*.tf) files with your desired resources.

From our testing the provider works well, there were few issues which were fixed recently (and few others pending with proposed fixes), and we are generally happy with how it works, though our mileage with is relatively short and in test/dev environments (at the moment).

**Comment by adam-f5** [comment]
Repository Archived
