### ISSUE TITLE
Most tests are skipped when submitting a PR

### ISSUE THREAD

**Issue by dannyk81** [f5devcentral/terraform-provider-bigip-old#94]
I Just noticed in Travis build logs in #91 and #93 that all test are skipped.

For example:
```
=== RUN   TestAccBigipCmDevice_create
--- SKIP: TestAccBigipCmDevice_create (0.00s)
	testing.go:427: Acceptance tests skipped unless env 'TF_ACC' set
=== RUN   TestAccBigipCmDevice_import
--- SKIP: TestAccBigipCmDevice_import (0.00s)
	testing.go:427: Acceptance tests skipped unless env 'TF_ACC' set
=== RUN   TestAccBigipCmDevicegroup_create
--- SKIP: TestAccBigipCmDevicegroup_create (0.00s)
	testing.go:427: Acceptance tests skipped unless env 'TF_ACC' set
```

https://travis-ci.org/f5devcentral/terraform-provider-bigip/builds/385525776?utm_source=github_status&utm_medium=notification

https://travis-ci.org/f5devcentral/terraform-provider-bigip/builds/386459045?utm_source=github_status&utm_medium=notification

**Comment by dannyk81** [comment]
@scshitole I guess that this is intentional, because you need a BigIP box to be able to run the tests against.

I wonder if you could deploy a VE BigIP box to be used for this? it would be great if the tests could run by the CI, instead of doing it manually, and I was lucky to have an F5 box for testing I guess most people won't have that.

**Comment by adam-f5** [comment]
Repository Archived
